# Generated by Django 2.0.4 on 2018-05-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.IntegerField(blank=True, null=True)),
                ('filename', models.CharField(blank=True, max_length=80, null=True)),
                ('frame', models.IntegerField(blank=True, null=True)),
                ('file_type', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('event_timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'security',
                'managed': False,
            },
        ),
    ]
